### ISSUE TITLE
js_of_ocaml examples links are dead

### ISSUE THREAD

**Issue by jchavarri** [ocsigen/ocsigen.github.io#39]
All the examples in the "Js_of_ocaml examples" section of the page http://ocsigen.org/js_of_ocaml/3.1.0/manual/overview are broken:

- http://ocsigen.org/js_of_ocaml/3.1.0/manual/files/toplevel/index.html
- http://ocsigen.org/js_of_ocaml/3.1.0/manual/files/planet/index.html
- http://ocsigen.org/js_of_ocaml/3.1.0/manual/files/graph_viewer/index.html
- etc.

The first one at least was working a week or two ago.

**Comment by balat** [comment]
solved
