### ISSUE TITLE
Announce Eliom 6.0 when done

### ISSUE THREAD

**Issue by vasilisp** [ocsigen/ocsigen.github.io#6]
See [draft](https://github.com/ocsigen/ocsigen.github.io/blob/d387b66e5661deaf4f7dededf83172fe3eb5bc1f/_drafts/eliom6.md).

Also take a look at the [migration guide](http://ocsigen.org/eliom/Eliom60).

Feel free to suggest modifications as needed (or do them yourselves).

CC @balat @vouillon @Drup @dannywillems.

**Comment by Drup** [comment]
Maybe mention compatibility with new ocaml versions ?

**Comment by vasilisp** [comment]
Sure, and compatibility in general (newer JSOO, newer TyXML).
